package cn.yooss.heic.linux;

/**
 * {@code /etc/os-release} of real distributions (the fields that matter, as the distributions ship them), for the
 * platform-neutral distribution and remedy tests.
 */
final class OsReleaseSamples {
  static final String UBUNTU_22_04 = String.join("\n",
    "PRETTY_NAME=\"Ubuntu 22.04.5 LTS\"",
    "NAME=\"Ubuntu\"",
    "VERSION_ID=\"22.04\"",
    "VERSION=\"22.04.5 LTS (Jammy Jellyfish)\"",
    "VERSION_CODENAME=jammy",
    "ID=ubuntu",
    "ID_LIKE=debian",
    "HOME_URL=\"https://www.ubuntu.com/\"",
    "UBUNTU_CODENAME=jammy");
  static final String UBUNTU_24_04 = String.join("\n",
    "PRETTY_NAME=\"Ubuntu 24.04.3 LTS\"",
    "NAME=\"Ubuntu\"",
    "VERSION_ID=\"24.04\"",
    "VERSION=\"24.04.3 LTS (Noble Numbat)\"",
    "VERSION_CODENAME=noble",
    "ID=ubuntu",
    "ID_LIKE=debian",
    "UBUNTU_CODENAME=noble",
    "LOGO=ubuntu-logo");
  static final String DEBIAN_12 = String.join("\n",
    "PRETTY_NAME=\"Debian GNU/Linux 12 (bookworm)\"",
    "NAME=\"Debian GNU/Linux\"",
    "VERSION_ID=\"12\"",
    "VERSION=\"12 (bookworm)\"",
    "VERSION_CODENAME=bookworm",
    "ID=debian");
  static final String DEBIAN_13 = String.join("\n",
    "PRETTY_NAME=\"Debian GNU/Linux 13 (trixie)\"",
    "NAME=\"Debian GNU/Linux\"",
    "VERSION_ID=\"13\"",
    "VERSION=\"13 (trixie)\"",
    "VERSION_CODENAME=trixie",
    "ID=debian");
  static final String DEBIAN_TESTING = String.join("\n",
    "PRETTY_NAME=\"Debian GNU/Linux forky/sid\"",
    "NAME=\"Debian GNU/Linux\"",
    "VERSION_CODENAME=forky",
    "ID=debian");
  static final String MINT_21 = String.join("\n",
    "NAME=\"Linux Mint\"",
    "VERSION=\"21.3 (Virginia)\"",
    "ID=linuxmint",
    "ID_LIKE=\"ubuntu debian\"",
    "PRETTY_NAME=\"Linux Mint 21.3\"",
    "VERSION_ID=\"21.3\"",
    "VERSION_CODENAME=virginia",
    "UBUNTU_CODENAME=jammy");
  static final String MINT_22 = String.join("\n",
    "NAME=\"Linux Mint\"",
    "VERSION=\"22 (Wilma)\"",
    "ID=linuxmint",
    "ID_LIKE=\"ubuntu debian\"",
    "PRETTY_NAME=\"Linux Mint 22\"",
    "VERSION_ID=\"22\"",
    "VERSION_CODENAME=wilma",
    "UBUNTU_CODENAME=noble");
  static final String LMDE_6 = String.join("\n",
    "PRETTY_NAME=\"LMDE 6 (faye)\"",
    "NAME=\"LMDE\"",
    "VERSION_ID=\"6\"",
    "VERSION=\"6 (faye)\"",
    "VERSION_CODENAME=faye",
    "ID=linuxmint",
    "ID_LIKE=debian",
    "DEBIAN_CODENAME=bookworm");
  static final String POP_22_04 = String.join("\n",
    "NAME=\"Pop!_OS\"",
    "VERSION=\"22.04 LTS\"",
    "ID=pop",
    "ID_LIKE=\"ubuntu debian\"",
    "PRETTY_NAME=\"Pop!_OS 22.04 LTS\"",
    "VERSION_ID=\"22.04\"",
    "VERSION_CODENAME=jammy",
    "UBUNTU_CODENAME=jammy");
  static final String KALI = String.join("\n",
    "PRETTY_NAME=\"Kali GNU/Linux Rolling\"",
    "NAME=\"Kali GNU/Linux\"",
    "VERSION_ID=\"2025.2\"",
    "VERSION=\"2025.2\"",
    "VERSION_CODENAME=kali-rolling",
    "ID=kali",
    "ID_LIKE=debian");
  static final String RASPBERRY_PI_OS_12 = String.join("\n",
    "PRETTY_NAME=\"Raspbian GNU/Linux 12 (bookworm)\"",
    "NAME=\"Raspbian GNU/Linux\"",
    "VERSION_ID=\"12\"",
    "VERSION=\"12 (bookworm)\"",
    "VERSION_CODENAME=bookworm",
    "ID=raspbian",
    "ID_LIKE=debian");
  static final String FEDORA_42 = String.join("\n",
    "NAME=\"Fedora Linux\"",
    "VERSION=\"42 (Workstation Edition)\"",
    "RELEASE_TYPE=stable",
    "ID=fedora",
    "VERSION_ID=42",
    "VERSION_CODENAME=\"\"",
    "PLATFORM_ID=\"platform:f42\"",
    "PRETTY_NAME=\"Fedora Linux 42 (Workstation Edition)\"",
    "CPE_NAME=\"cpe:/o:fedoraproject:fedora:42\"");
  static final String NOBARA_42 = String.join("\n",
    "NAME=\"Nobara Linux\"",
    "VERSION=\"42 (KDE Plasma Desktop Edition)\"",
    "ID=nobara",
    "ID_LIKE=\"rhel centos fedora\"",
    "VERSION_ID=42",
    "PLATFORM_ID=\"platform:f42\"",
    "PRETTY_NAME=\"Nobara Linux 42 (KDE Plasma Desktop Edition)\"");
  static final String ALMALINUX_9 = String.join("\n",
    "NAME=\"AlmaLinux\"",
    "VERSION=\"9.6 (Sage Margay)\"",
    "ID=\"almalinux\"",
    "ID_LIKE=\"rhel centos fedora\"",
    "VERSION_ID=\"9.6\"",
    "PLATFORM_ID=\"platform:el9\"",
    "PRETTY_NAME=\"AlmaLinux 9.6 (Sage Margay)\"");
  static final String ROCKY_9 = String.join("\n",
    "NAME=\"Rocky Linux\"",
    "VERSION=\"9.6 (Blue Onyx)\"",
    "ID=\"rocky\"",
    "ID_LIKE=\"rhel centos fedora\"",
    "VERSION_ID=\"9.6\"",
    "PLATFORM_ID=\"platform:el9\"",
    "PRETTY_NAME=\"Rocky Linux 9.6 (Blue Onyx)\"");
  static final String RHEL_9 = String.join("\n",
    "NAME=\"Red Hat Enterprise Linux\"",
    "VERSION=\"9.6 (Plow)\"",
    "ID=\"rhel\"",
    "ID_LIKE=\"fedora\"",
    "VERSION_ID=\"9.6\"",
    "PLATFORM_ID=\"platform:el9\"",
    "PRETTY_NAME=\"Red Hat Enterprise Linux 9.6 (Plow)\"");
  static final String CENTOS_STREAM_10 = String.join("\n",
    "NAME=\"CentOS Stream\"",
    "VERSION=\"10 (Coughlan)\"",
    "ID=\"centos\"",
    "ID_LIKE=\"rhel fedora\"",
    "VERSION_ID=\"10\"",
    "PLATFORM_ID=\"platform:el10\"",
    "PRETTY_NAME=\"CentOS Stream 10 (Coughlan)\"");
  static final String TUMBLEWEED = String.join("\n",
    "NAME=\"openSUSE Tumbleweed\"",
    "# VERSION=\"20250901\"",
    "ID=\"opensuse-tumbleweed\"",
    "ID_LIKE=\"opensuse suse\"",
    "VERSION_ID=\"20250901\"",
    "PRETTY_NAME=\"openSUSE Tumbleweed\"");
  static final String SLOWROLL = String.join("\n",
    "NAME=\"openSUSE Slowroll\"",
    "ID=\"opensuse-slowroll\"",
    "ID_LIKE=\"opensuse suse opensuse-tumbleweed\"",
    "VERSION_ID=\"20250901\"",
    "PRETTY_NAME=\"openSUSE Slowroll\"");
  static final String LEAP_15_6 = String.join("\n",
    "NAME=\"openSUSE Leap\"",
    "VERSION=\"15.6\"",
    "ID=\"opensuse-leap\"",
    "ID_LIKE=\"suse opensuse\"",
    "VERSION_ID=\"15.6\"",
    "PRETTY_NAME=\"openSUSE Leap 15.6\"");
  static final String SLES_15 = String.join("\n",
    "NAME=\"SLES\"",
    "VERSION=\"15-SP6\"",
    "VERSION_ID=\"15.6\"",
    "PRETTY_NAME=\"SUSE Linux Enterprise Server 15 SP6\"",
    "ID=\"sles\"",
    "ID_LIKE=\"suse\"");
  static final String ARCH = String.join("\n",
    "NAME=\"Arch Linux\"",
    "PRETTY_NAME=\"Arch Linux\"",
    "ID=arch",
    "BUILD_ID=rolling",
    "ANSI_COLOR=\"38;2;23;147;209\"");
  static final String MANJARO = String.join("\n",
    "NAME=\"Manjaro Linux\"",
    "PRETTY_NAME=\"Manjaro Linux\"",
    "ID=manjaro",
    "ID_LIKE=arch",
    "BUILD_ID=rolling");
  static final String ENDEAVOUROS = String.join("\n",
    "NAME='EndeavourOS'",
    "PRETTY_NAME='EndeavourOS'",
    "ID='endeavouros'",
    "ID_LIKE='arch'",
    "BUILD_ID='2025.03.19'");
  static final String ALPINE_3_22 = String.join("\n",
    "NAME=\"Alpine Linux\"",
    "ID=alpine",
    "VERSION_ID=3.22.1",
    "PRETTY_NAME=\"Alpine Linux v3.22\"");
  static final String NIXOS = String.join("\n",
    "ANSI_COLOR=\"0;38;2;126;186;228\"",
    "BUILD_ID=\"25.05.20250901.abcdef0\"",
    "ID=nixos",
    "NAME=NixOS",
    "PRETTY_NAME=\"NixOS 25.05 (Warbler)\"",
    "VERSION_CODENAME=warbler",
    "VERSION_ID=\"25.05\"");
  static final String GENTOO = String.join("\n",
    "NAME=Gentoo",
    "ID=gentoo",
    "PRETTY_NAME=\"Gentoo Linux\"",
    "VERSION_ID=\"2.17\"");
  /** Inside a Flatpak sandbox: the os-release of the freedesktop runtime (org.freedesktop.Platform / .Sdk 26.08). */
  static final String FREEDESKTOP_26_08 = String.join("\n",
    "NAME=\"Freedesktop SDK\"",
    "VERSION=\"26.08 (Flatpak runtime)\"",
    "ID=org.freedesktop.platform",
    "VERSION_ID=26.08",
    "PRETTY_NAME=\"Freedesktop SDK 26.08 (Flatpak runtime)\"");
  static final String FREEDESKTOP_25_08 = FREEDESKTOP_26_08.replace("26.08", "25.08");
  static final String FREEDESKTOP_24_08 = FREEDESKTOP_26_08.replace("26.08", "24.08");

  private OsReleaseSamples() {
  }

  static LinuxDistribution parse(String osRelease) {
    return LinuxDistribution.parse(osRelease, false, false);
  }
}
